error: package directory 'python/gps_driver' does not exist
